Add `function.prototype.name` shim
airbnb/browser-shims pull request #15
Opened 2017-07-11 00:27 UTC by raejin

As title.

2017-07-11 06:44 UTC, ljharb requested changes
LGTM pending https://github.com/ljharb/function.prototype.name/pull/13 and this change

2017-07-11 06:44 UTC, ljharb commented on package.json
> +  "version": "1.12.0",
This should be reverted; version numbers should never be bumped in PRs.

2017-07-12 05:25 UTC, raejin commented
@ljharb Good to go!

2017-07-12 07:57 UTC, ljharb commented on browser-only.js
> +require('function.prototype.name').shim();
i feel like maybe this would be better in js-shims, but in an IE 9-11 target. Let's chat about it tomorrow.

2017-07-12 15:52 UTC, raejin commented on browser-only.js
> +require('function.prototype.name').shim();
Sounds good to me. I agree it is more of a js-shim.

2017-07-13 17:24 UTC, raejin commented
After some reflection, @ljharb:

Since this is a IE specific issue, regardless of pre or post ECMAScript5, should we shim this in browser shims instead?

2017-07-14 22:26 UTC, ljharb commented
Since this is a language feature, and there's no way to target IE 10 or 11 (since they lack conditional comments), this has been added to `airbnb-js-shims` v1.2.0.

2017-07-14 22:26 UTC, closed without merging