Add CustomEvent polyfill for browser only
airbnb/browser-shims pull request #16
Opened 2017-08-10 21:27 UTC by raejin

Adding CustomEvent support for IEs.

2017-08-10 21:40 UTC, ljharb commented on browser-only.js
> +  require('custom-event-polyfill');
Any reason to prefer this one, vs https://www.npmjs.com/package/custom-event? I have no preference, just want to make sure we're using the best/most maintained one.

2017-08-10 21:58 UTC, raejin commented on browser-only.js
> +  require('custom-event-polyfill');
@ljharb I think I got fooled by SEO, was not aware of this. I'll update accordingly. Thanks for catching this.

2017-08-10 22:18 UTC, raejin commented
Confirmed working in IE9, IE10, and IE11.

2017-08-10 23:03 UTC, ljharb approved these changes
LGTM

2017-08-10 23:03 UTC, ljharb requested changes
Oh, actually, let's add this to the readme too :-)

2017-08-10 23:42 UTC, raejin commented
@ljharb updated!

2017-08-10 23:46 UTC, ljharb commented on README.md
> + - [custom-event](https://www.npmjs.com/package/custom-event) - CustomEvent polyfill (only in browsers)
it's not only in browsers tho, is it? it looks like it's doing it in node too

2017-08-11 21:14 UTC, ljharb approved these changes

2017-08-11 21:15 UTC, merged

2017-08-11 21:20 UTC, ljharb commented
Ended up reverting this by rewinding; we don't need it long term.