Add intersection-observer
airbnb/browser-shims pull request #22
Opened 2018-12-07 21:31 UTC by lencioni

This will allow us to safely use IntersectionObserver.

https://github.com/w3c/IntersectionObserver/tree/master/polyfill

2018-12-07 22:05 UTC, ljharb requested changes
Let's update the readme as well

2018-12-07 22:05 UTC, ljharb commented on browser-only.js
> +require('intersection-observer');
i think this needs to go in the "if there's a window" block

2018-12-07 22:42 UTC, lencioni commented
@lencioni updated, PTAL!

2018-12-08 08:00 UTC, ljharb approved these changes

2018-12-08 08:00 UTC, merged