Add KeyboardEvent.key shim
airbnb/browser-shims pull request #23
Opened 2019-01-26 01:07 UTC by indiesquidge

Please let me know what the requisite next steps would be to getting this shim available for use!

Ref: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

2019-01-26 01:08 UTC, indiesquidge commented on package.json
> +    "shim-keyboard-event-key": "git+https://github.com/shvaikalesh/shim-keyboard-event-key.git",
Whoops, this doesn't look right.

2019-01-26 08:11 UTC, ljharb requested changes

2019-01-26 08:11 UTC, ljharb commented on browser-only.js
> +require('shim-keyboard-event-key');
this is failing travis because `KeyboardEvent` doesn't exist; I think you need to move it into the "it's a browser" block below.

2019-02-24 01:23 UTC, indiesquidge commented
@ljharb, moved the import to the proper place, thanks!

2019-02-24 06:24 UTC, ljharb approved these changes

2019-02-24 06:28 UTC, merged