[New] Adding console.* polyfill
airbnb/browser-shims pull request #7
Opened 2016-11-23 20:17 UTC by nicksorrentino

While IE9 is still supported add a polyfill for console.* statement

@pnachum @ljharb

2016-11-23 20:27 UTC, lencioni approved these changes

2016-11-23 20:27 UTC, lencioni commented on index.js
> +// console.* polyfill for old browsers
It would be nice if we could be more specific about which browsers.

2016-11-23 20:49 UTC, nicksorrentino commented
Okay updated the comment.

2016-11-23 20:56 UTC, lencioni commented
Will you rebase this so it does not contain any merge commits?

2016-11-23 21:10 UTC, nicksorrentino commented
okay rebased

2016-11-23 22:03 UTC, ljharb reviewed
I don't think we should do this.

The proper solution is to write tests for all our code, since console warnings fail tests - in other words, this only prevents breakage in code that's already broken (since code without tests is broken by default).

2016-11-23 22:04 UTC, ljharb requested changes

2016-11-23 22:04 UTC, ljharb commented on index.js
> +require('console-polyfill')
semicolon

2016-11-23 22:17 UTC, nicksorrentino commented on index.js
> +require('console-polyfill')
Whoops, when I rebased it reverted the fix I had locally.

2016-11-23 22:21 UTC, nicksorrentino commented
Okay @ljharb based on the post mortem is seemed like a reasonable idea, it seemed like this was low effort and high-reward for the case when people eslint-disable.  Regardless if you prefer to keep the current behavior thats fine.

2016-11-23 22:24 UTC, ljharb commented
@nicksorrentino hopefully nobody ever blindly does `eslint-disable` and only disables specific rules :-/

2016-11-23 22:58 UTC, nicksorrentino commented
I mean more a specific rule so they can do a console.log or warn.  I think if we don't want this then we need to make console statements a error in eslint.  We do have some branches where they are only an eslint warn.

2016-11-23 23:24 UTC, pnachum commented
I disagree with @ljharb on this one. 
1. It would be great if all of our code was tested, but it's not
2. For whatever reason, the warning from DLS did not break tests in monorail. 
3. If all else fails, as it did in my case (ie I saw no lint/test failures), it would be better to not break the page. 

Is there any downside to adding this?

2016-11-23 23:25 UTC, pnachum commented
Also, doesn't `console.log` also break IE9, but not fail tests?

2016-11-24 04:02 UTC, ljharb commented
Yes, those are good points that our tests don't fail on `console.log`, and that "if all else fails, it'd be better not to break the page".

2016-11-24 04:02 UTC, ljharb approved these changes
I still don't like needing to do this, but good points have been made.

2016-11-24 05:47 UTC, merged

2016-11-24 06:36 UTC, ljharb commented
Released as v1.5.0